name: fyp1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
 # Firebase dependencies
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  firebase_analytics: ^11.4.4

  # Other essential packages
  go_router: ^14.3.0
  auto_size_text: ^3.0.0
  fl_chart: ^0.70.2
  percent_indicator: ^4.2.2
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  google_sign_in: ^6.2.1
  image_picker: ^1.1.0
  intl: ^0.20.2
  audioplayers: ^6.4.0
  video_player: ^2.5.1
  youtube_player_flutter: ^9.1.1
  flutter_colorpicker: ^1.0.3
  tutorial_coach_mark: ^1.2.13
  share_plus: ^10.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
  - assets/SplashScreen1.png
  - assets/SplashScreen2.png
  - assets/SplashScreen3.png
  - assets/logo.png
  - assets/
  - assets/Animation/child.png
  - assets/Animation/book.png
  - assets/Animation/teacher.png
  - assets/Animation/quiz.png
  - assets/Animation/chapter.png
  - assets/Animation/congratulation.png
  - assets/Animation/design1.png
  - assets/Animation/design2.png
  - assets/Animation/design3.png
  - assets/Animation/gamelogo.png
  - assets/Animation/error.png
  - assets/Animation/profile.png
  - assets/Animation/loading.gif
  - assets/Animation/shoppingbackground.png
  - assets/Animation/profilebackground.png
  - assets/Animation/shoes.png
  - assets/Animation/tshirt.png
  - assets/Animation/hat.png
  - assets/Animation/skirt.png
  - assets/Animation/coffee.png
  - assets/Animation/coffeebackground.png
  - assets/Animation/abtesting.png
  - assets/Animation/flowa.png
  - assets/Animation/flowb.png
  - assets/Animation/hci.png
  - assets/Animation/notelistbackground.png



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
