class NoteProgress {
  String? progressID;  // Unique ID for progress (Auto-generated by Firestore)
  final String studentID;      // ID of the student
  final String chapterID;   // ID of the chapter
  final Map<String, String> progress;  // Map of noteID -> progress status ("Completed", "In Progress", etc.)

  NoteProgress({
    this.progressID,
    required this.studentID,
    required this.chapterID,
    required this.progress,
  });

  // Factory constructor for creating a NoteProgress from JSON
  factory NoteProgress.fromJson(Map<String, dynamic> json) {
    return NoteProgress(
      progressID: json['progressID'] as String?,
      studentID: json['studentID'] ,
      chapterID: json['chapterID'] as String,
      progress: Map<String, String>.from(json['progress'] as Map<String, dynamic>),
    );
  }

  // Convert a NoteProgress instance to JSON
  Map<String, dynamic> toJson() {
    return {
      'progressID': progressID,
      'studentID': studentID,
      'chapterID': chapterID,
      'progress': progress,
    };
  }
}
