class NoteProgress {
  String? progressID;  // Unique ID for progress (Auto-generated by Firestore)
  final String studentID;      // ID of the student
  final String chapterID;   // ID of the chapter
  final Map<String, String> progress;  // Map of noteID -> progress status ("Completed", "In Progress", etc.)

  NoteProgress({
    this.progressID,
    required this.studentID,
    required this.chapterID,
    required this.progress,
  });

  // Factory constructor for creating a NoteProgress from JSON
 factory NoteProgress.fromJson(String progressID, Map<String, dynamic> json) {
  return NoteProgress(
    progressID: progressID,  // Assign the document ID as progressID
    studentID: json['studentID'],
    chapterID: json['chapterID'],
    progress: Map<String, String>.from(json['progress']),
  );
}
  // Convert a NoteProgress instance to JSON
  Map<String, dynamic> toJson() {
    return {
    
      'studentID': studentID,
      'chapterID': chapterID,
      'progress': progress,
    };
  }
}
