// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAAqZyvs_zfzNS_qyHE_emIO0IR0hHzKg',
    appId: '1:1009963429547:web:64d93325ca6915751811ee',
    messagingSenderId: '1009963429547',
    projectId: 'hcimastery',
    authDomain: 'hcimastery.firebaseapp.com',
    storageBucket: 'hcimastery.firebasestorage.app',
    measurementId: 'G-1HWXZC41RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP76VLssqiTosEaibGPd7s7yLnk4BPCbw',
    appId: '1:1009963429547:android:80796894c99ca55e1811ee',
    messagingSenderId: '1009963429547',
    projectId: 'hcimastery',
    storageBucket: 'hcimastery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvtonUsOoTj0a823sMTqWF5MI44VUagaY',
    appId: '1:1009963429547:ios:486fca81e8a5d4041811ee',
    messagingSenderId: '1009963429547',
    projectId: 'hcimastery',
    storageBucket: 'hcimastery.firebasestorage.app',
    iosBundleId: 'com.example.fyp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvtonUsOoTj0a823sMTqWF5MI44VUagaY',
    appId: '1:1009963429547:ios:486fca81e8a5d4041811ee',
    messagingSenderId: '1009963429547',
    projectId: 'hcimastery',
    storageBucket: 'hcimastery.firebasestorage.app',
    iosBundleId: 'com.example.fyp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAAqZyvs_zfzNS_qyHE_emIO0IR0hHzKg',
    appId: '1:1009963429547:web:13c121f2e1d44ea31811ee',
    messagingSenderId: '1009963429547',
    projectId: 'hcimastery',
    authDomain: 'hcimastery.firebaseapp.com',
    storageBucket: 'hcimastery.firebasestorage.app',
    measurementId: 'G-ZMSQ66KLP8',
  );
}
